package com.kgav.gw.assetmanage.asset.dto

data class AsmodifyRequest(
    val itemdcd: String,
    val ano: Int,
    val anm: String?,
    val acorpcd: String?,
    val apart: String?,
    val auser: String?,
    val myear: Int?,
    val mcorp: String?,
    val astate: String?,
    val regid: String?,
    val regip: String?,
    val regdt: String?,
    val attr1: String?,
    val attr2: String?,
    val attr3: String?,
    val attr4: String?,
    val attr5: String?,
    val iyear: String?,
    val aplace: String?,
    val spec: String?,
    val price: String?,
    val acdid: String?,
)
