package com.kgav.gw.assetmanage.asset.dto.response

data class AsdetailResponse(
    val itemdcd: String?,
    val item4nm: String?,
    val item4cd: String?,
    val ano: Int?,
    val acdid: String?,
    val anm: String?,
    val amodelno: String?,
    val amodelnm: String?,
    val conm: String?,
    val acorpcd: String?,
    val acorp: String?,
    val apart: String?,
    val auser: String?,
    val myear: String?,
    val mcorp: String?,
    val statenm: String?,
    val item1cd: String?,
    val item2cd: String?,
    val item3cd: String?,
    val regid: String?,
    val regip: String?,
    val regdt: String?,
    val attr1: String?,
    val attr2: String?,
    val attr3: String?,
    val attr4: String?,
    val attr5: String?,
    val iyear: String?,
    val aplace: String?,
    val spec: String?,
    val price: String?
)
