package com.kgav.gw.assetmanage.swlicense.dto.request

data class SwaddRequest(
    val swno : String?,
    val itemdcd : String?,
    val swnm : String?,
    val mcorp : String?,
    val myear : String?,
    val ugubun : String?,
    val lgubun : String?,
    val lqty : String?,
    val rqty : String?,
    val lsdate : String?,
    val ledate : String?,
    val astate : String?,
    val iyear : String?,
    val price : String?,
    val aplace : String?,
    val apart : String?,
    val acorp : String?,
    val auser : String?,
    val acorpcd : String?,
    var regid : String?,
    var regip : String?,
    val spec : String?,
    val attr1 : String?,
    val attr2 : String?,
)
